apiVersion: apps/v1
kind: Deployment
spec:
  selector:
    matchLabels:
      app: cv-website
  template:
    spec:
      containers:
        - name: cv-website
          image: your_registry/cv-website:latest
          ports:
            - containerPort: 80
              name: http
          env:
            - name: VITE_FIRST_NAME
              value: "Abubtiyar"
            - name: VITE_LAST_NAME
              value: "Bubur"
            - name: VITE_OCCUPATION
              value: "Senior Backend Engineer"
            - name: VITE_CITY
              value: "R'lyeh"
            - name: VITE_PHONE
              value: "+66 666 666-66-666"
            - name: VITE_EMAIL
              value: "abubtiyar@domain.com"
            - name: VITE_GITHUB
              value: "https://github.com/test"
            - name: VITE_LINKEDIN
              value: "https://linkedin.com/in/test"
          resources:
            limits:
              memory: 256Mi
              cpu: 200m
            requests:
              cpu: 100m
              memory: 128Mi
          volumeMounts:
            - name: pages
              mountPath: /md/
      volumes:
        - name: pages
          configMap:
            name: pages