server {
    listen       80;
    listen  [::]:80;
    server_name  localhost;

    location / {
        root   /usr/share/nginx/html;
        try_files $uri $uri/ /index.html;
    }

    location /md {
        alias /md;
        autoindex on;
        autoindex_format json;
    }

    # Serve runtime environment variables as config.js
    location /config.js {
        root /usr/share/nginx/html;
        default_type application/javascript;
    }
}